# Generated by Django 4.2.3 on 2024-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='authorization',
            field=models.BooleanField(default=False),
        ),
    ]
